[package]
name = "crc8-cdma2000-fast"
version = "0.2.0"
edition = "2021"

[dependencies]
crc-fast-gen = { path = "../crc-fast-gen" }

[dev-dependencies]
criterion = "0.5"

[lib]
bench = false

[[bench]]
name = "fast_vs_fallback"
harness = false