[package]
name = "$PACKAGE_NAME"
version = "$VERSION"
edition = "2021"

[dependencies]
crc-fast-gen = { path = "../crc-fast-gen" }

[dev-dependencies]
criterion = {version = "0.5", features = ["html_reports"] }

[lib]
bench = false

[[bench]]
name = "fast_vs_fallback"
harness = false